# Site settings
title: murriel
email: hi@murrielgrace.com
url: https://www.murrielgrace.com
description: "unpixelated chaos"
  # "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: murrielgrace.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/xmurriel
  - title: hackaday
    url: https://hackaday.io/murriel
  - title: github
    url: https://github.com/murriel
  - title: linkedin
    url: https://www.linkedin.com/in/murrielperez
  - title: keybase
    url: https://www.keybase.io/murriel
# Build settings
markdown: kramdown
permalink: pretty
